### PR TITLE
Don't try to call `_repr_*_` on a class

### LINKED ISSUE #816: showable error on certain objects
On PyCall v1.91.4, Julia 1.5,

```julia
julia> using Conda, PyCall

julia> Conda.add("scikit-learn")   # sorry that it's such a big package

julia> showable(MIME"text/html"(), pyimport("sklearn.linear_model").LogisticRegression)
ERROR: PyError ($(Expr(:escape, :(ccall(#= /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
TypeError("'property' object is not callable")

Stacktrace:
 [1] pyerr_check at /Users/cedric/.julia/packages/PyCall/zqDXB/src/exception.jl:60 [inlined]
 [2] pyerr_check at /Users/cedric/.julia/packages/PyCall/zqDXB/src/exception.jl:64 [inlined]
 [3] _handle_error(::String) at /Users/cedric/.julia/packages/PyCall/zqDXB/src/exception.jl:81
 [4] macro expansion at /Users/cedric/.julia/packages/PyCall/zqDXB/src/exception.jl:95 [inlined]
 [5] #110 at /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:43 [inlined]
 [6] disable_sigint at ./c.jl:446 [inlined]
 [7] __pycall! at /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:42 [inlined]
 [8] _pycall!(::PyObject, ::PyObject, ::Tuple{}, ::Int64, ::Ptr{Nothing}) at /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:29
 [9] _pycall! at /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:11 [inlined]
 [10] #pycall#115 at /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:80 [inlined]
 [11] pycall at /Users/cedric/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:80 [inlined]
 [12] showable(::MIME{Symbol("text/html")}, ::PyObject) at /Users/cedric/.julia/packages/PyCall/zqDXB/src/PyCall.jl:894
 [13] top-level scope at REPL[25]:1
```

For context, https://github.com/fonsp/Pluto.jl/issues/412

It might be a scikit-learn issue, but the error message is pretty cryptic.

### PR DESCRIPTION
**Pull request by tkf**
fix #816

An MWE

```julia
py"""
class Issue816(object):
    def _repr_html_(self):
        return "<h1>Issue816</h1>"
"""

showable("text/html", py"Issue816()")  # => true
showable("text/html", py"Issue816")  # => throws
```

```
ERROR: PyError ($(Expr(:escape, :(ccall(#= /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
TypeError("_repr_html_() missing 1 required positional argument: 'self'")

Stacktrace:
 [1] pyerr_check at /home/takafumi/.julia/dev/PyCall/src/exception.jl:62 [inlined]
 [2] pyerr_check at /home/takafumi/.julia/dev/PyCall/src/exception.jl:66 [inlined]
 [3] _handle_error(::String) at /home/takafumi/.julia/dev/PyCall/src/exception.jl:83
 [4] macro expansion at /home/takafumi/.julia/dev/PyCall/src/exception.jl:97 [inlined]
 [5] #110 at /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:43 [inlined]
 [6] disable_sigint at ./c.jl:446 [inlined]
 [7] __pycall! at /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:42 [inlined]
 [8] _pycall!(::PyObject, ::PyObject, ::Tuple{}, ::Int64, ::Ptr{Nothing}) at /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:29
 [9] _pycall! at /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:11 [inlined]
 [10] #pycall#115 at /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:80 [inlined]
 [11] pycall at /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:80 [inlined]
 [12] showable(::MIME{Symbol("text/html")}, ::PyObject) at /home/takafumi/.julia/dev/PyCall/src/PyCall.jl:901
 [13] showable(::String, ::Any) at ./multimedia.jl:77
 [14] top-level scope at /home/takafumi/.julia/dev/PyCall/src/pyeval.jl:232
```

The error is due to invoking `Issue816._repr_html_()`. A simple solution seems to just return `false` from `showable("text/html", o)` when `o` is a python type. Although it's probably technically possible to implement `_repr_html_` on classes as well, it's very likely virtually nobody uses it.

### CODE REVIEW

File: src/PyCall.jl [hunk 1]
```diff
@@ -897,7 +897,10 @@ for (mime, method) in ((MIME"text/html", "_repr_html_"),
             throw(MethodError(show, (io, mime, o)))
         end
         Base.showable(::$mime, o::PyObject) =
-            !ispynull(o) && hasproperty(o, $method) && let meth = o.$method
+            !ispynull(o) &&
+            !pyisinstance(o, @pyglobalobj :PyType_Type) &&  # issue 816
```
Comment (stevengj) [inline src/PyCall.jl:901]: Can we use `PyCallable_Check` instead?

Comment (tkf) [reply src/PyCall.jl:901]: `Issue816._repr_html_` in the OP is callable so I'm not sure if `PyCallable_Check` is enough. But maybe `PyMethod_Check` would work? I'll check.

**Comment by tkf** [comment]
I considered a few approaches. I think the best way to do this to port [`IPython.utils.dir2.get_real_method`](https://github.com/ipython/ipython/blob/7.9.0/IPython/utils/dir2.py) to Julia (or we can just copy `dir2.py` but it doesn't seem like the traditional approach that PyCall.jl takes). I don't think it covers all edge cases I had in mind (e.g., descriptors) but we don't really need to support edge cases than IPython does. Since Python classes with special `_repr_*_` methods are likely to be tested with IPython, following IPython's logic sounds like the best approach.

I think this is good to go.

(Side notes: 95ee1f13da685ebfb9777f4558acca59e0effa46 implements one of the alternative methods by using `inspect.signature`. I think it's a bit more accurate than IPython's `get_real_method`. However, it's much more complicated. I also considered "easier to ask for forgiveness than permission" approach. But I think it's better to stick with IPython's approach.)

**Comment by stevengj** [comment]
LGTM — `get_real_method` is a bit wacky but Python is messy at this level.
