### PR TITLE
[RFC] Throw a special exceptions in Julia callbacks (Fix #770)

### LINKED ISSUE #770: Julia Stack Traces thrown during python execution lose formatting
Look at this beautiful stack trace
```
julia> error("I am beautiful")
ERROR: I am beautiful
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at REPL[20]:1
 [3] eval(::Module, ::Any) at ./boot.jl:331
 [4] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [5] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [6] top-level scope at none:0
```

now look at this. It's very ugly.
```
julia> using PyCall
julia> py"$error('I am ugly')"
ERROR: PyError ($(Expr(:escape, :(ccall(#= /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'RuntimeError'>
RuntimeError('Julia exception: I am ugly\nStacktrace:\n [1] error(::String) at ./error.jl:33\n [2] #invokelatest#1 at ./essentials.jl:712 [inlined]\n [3] invokelatest(::Any, ::Any) at ./essentials.jl:711\n [4] _pyjlwrap_call(::Function, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/callback.jl:28\n [5] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/callback.jl:49\n [6] macro expansion at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:93 [inlined]\n [7] #120 at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 [inlined]\n [8] disable_sigint at ./c.jl:446 [inlined]\n [9] pyeval_(::String, ::PyDict{String,PyObject,true}, ::PyDict{String,PyObject,true}, ::Int64, ::String) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:37\n [10] top-level scope at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:230\n [11] eval(::Module, ::Any) at ./boot.jl:331\n [12] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86\n [13] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073\n [14] top-level scope at none:0\n [15] eval(::Module, ::Any) at ./boot.jl:331\n [16] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86\n [17] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]\n [18] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358')
  File "/Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl", line 1, in <module>
    const Py_single_input = 256  # from Python.h

Stacktrace:
 [1] pyerr_check at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:60 [inlined]
 [2] pyerr_check at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:64 [inlined]
 [3] _handle_error(::String) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:81
 [4] macro expansion at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:95 [inlined]
 [5] #120 at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 [inlined]
 [6] disable_sigint at ./c.jl:446 [inlined]
 [7] pyeval_(::String, ::PyDict{String,PyObject,true}, ::PyDict{String,PyObject,true}, ::Int64, ::String) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:37
 [8] top-level scope at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:230
 [9] eval(::Module, ::Any) at ./boot.jl:331
 [10] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [11] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [12] top-level scope at none:0
```

In particular notice that the newlines in the Julia's stack traces are printed as \n in python.
Is there a way to improve this?

### PR DESCRIPTION
**Pull request by PhilipVinc**
This PR tries to address the printing of stack traces in Julia callbacks and fix #770, while also leaving the door open for further improvements.

The problem I wanted to solve is the fact that errors and stack traces thrown by a Julia callback executed by python, such as 
```python
julia> py"$error('I am ugly')"
```
loses formatting when being displayed. 
This is because currently we _render_ the exception to a string when it is thrown, return it to python as a python error, which then is returned to Julia again, and displays it.

This is especially painful in wrapper packages such as Tensorflow.jl, Jax.jl or several others.

In the process formatting is lost. 

My solution:
When a Julia callback throws, don't render the callback immediately. Instead return a custom Error type, `PyJlError`, which stores the backtrace.

When control is eventually returned to Julia, check if the python error is wrapping a Julia error. If so, show only the Julia one.

This is compatible with JuliaPy, as the rendering of `PyJlError` is handled by the show method.

Result:
old:
```Julia
julia> using PyCall
julia> py"$error('I am ugly')"
ERROR: PyError ($(Expr(:escape, :(ccall(#= /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'RuntimeError'>
RuntimeError('Julia exception: I am ugly\nStacktrace:\n [1] error(::String) at ./error.jl:33\n [2] #invokelatest#1 at ./essentials.jl:712 [inlined]\n [3] invokelatest(::Any, ::Any) at ./essentials.jl:711\n [4] _pyjlwrap_call(::Function, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/callback.jl:28\n [5] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/callback.jl:49\n [6] macro expansion at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:93 [inlined]\n [7] #120 at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 [inlined]\n [8] disable_sigint at ./c.jl:446 [inlined]\n [9] pyeval_(::String, ::PyDict{String,PyObject,true}, ::PyDict{String,PyObject,true}, ::Int64, ::String) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:37\n [10] top-level scope at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:230\n [11] eval(::Module, ::Any) at ./boot.jl:331\n [12] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86\n [13] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073\n [14] top-level scope at none:0\n [15] eval(::Module, ::Any) at ./boot.jl:331\n [16] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86\n [17] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]\n [18] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358')
  File "/Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl", line 1, in <module>
    const Py_single_input = 256  # from Python.h

Stacktrace:
 [1] pyerr_check at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:60 [inlined]
 [2] pyerr_check at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:64 [inlined]
 [3] _handle_error(::String) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:81
 [4] macro expansion at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/exception.jl:95 [inlined]
 [5] #120 at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 [inlined]
 [6] disable_sigint at ./c.jl:446 [inlined]
 [7] pyeval_(::String, ::PyDict{String,PyObject,true}, ::PyDict{String,PyObject,true}, ::Int64, ::String) at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:37
 [8] top-level scope at /Users/filippovicentini/.julia/packages/PyCall/zqDXB/src/pyeval.jl:230
 [9] eval(::Module, ::Any) at ./boot.jl:331
 [10] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [11] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [12] top-level scope at none:0
```

new:
```Julia
julia> py"$error('I am ugly')"
ERROR: An error occured in a Julia function called from Python
I am ugly
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [3] invokelatest(::Any, ::Any) at ./essentials.jl:711
 [4] _pyjlwrap_call(::Function, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /Users/filippovicentini/.julia/dev/PyCall/src/callback.jl:28
 [5] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /Users/filippovicentini/.julia/dev/PyCall/src/callback.jl:49
 [6] macro expansion at /Users/filippovicentini/.julia/dev/PyCall/src/exception.jl:117 [inlined]
 [7] #120 at /Users/filippovicentini/.julia/dev/PyCall/src/pyeval.jl:38 [inlined]
 [8] disable_sigint at ./c.jl:446 [inlined]
 [9] pyeval_(::String, ::PyDict{String,PyObject,true}, ::PyDict{String,PyObject,true}, ::Int64, ::String) at /Users/filippovicentini/.julia/dev/PyCall/src/pyeval.jl:37
 [10] top-level scope at /Users/filippovicentini/.julia/dev/PyCall/src/pyeval.jl:230
 [11] eval(::Module, ::Any) at ./boot.jl:331
 [12] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [13] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [14] top-level scope at none:0
 [15] eval(::Module, ::Any) at ./boot.jl:331
 [16] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [17] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
 [18] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358
Stacktrace:
 [1] pyerr_check at /Users/filippovicentini/.julia/dev/PyCall/src/exception.jl:84 [inlined]
 [2] pyerr_check at /Users/filippovicentini/.julia/dev/PyCall/src/exception.jl:88 [inlined]
 [3] _handle_error(::String) at /Users/filippovicentini/.julia/dev/PyCall/src/exception.jl:105
 [4] macro expansion at /Users/filippovicentini/.julia/dev/PyCall/src/exception.jl:119 [inlined]
 [5] #120 at /Users/filippovicentini/.julia/dev/PyCall/src/pyeval.jl:38 [inlined]
 [6] disable_sigint at ./c.jl:446 [inlined]
 [7] pyeval_(::String, ::PyDict{String,PyObject,true}, ::PyDict{String,PyObject,true}, ::Int64, ::String) at /Users/filippovicentini/.julia/dev/PyCall/src/pyeval.jl:37
 [8] top-level scope at /Users/filippovicentini/.julia/dev/PyCall/src/pyeval.jl:230
 [9] eval(::Module, ::Any) at ./boot.jl:331
 [10] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [11] run_backend(::REPL.REPLBackend) at /Users/filippovicentini/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [12] top-level scope at none:0
```

### CODE REVIEW

File: src/exception.jl [hunk 1]
```diff
@@ -1,3 +1,17 @@
+#########################################################################
+# A wrapper around an error that happened in a Julia callback
+
+struct PyJlError{E<:Exception} <: Exception
+    err::E
+    trace
+end
+
+function show(io::IO, e::PyJlError)
+    println(io, "An error occured in a Julia function called from Python")
```
Comment (stevengj) [inline src/exception.jl:10]: Maybe a period or a colon at the end of this sentence?

File: src/exception.jl [hunk 2]
```diff
@@ -12,15 +26,6 @@ struct PyError <: Exception
...
     # indicator.
-    function PyError(msg::AbstractString)
-        ptype, pvalue, ptraceback = Ref{PyPtr}(), Ref{PyPtr}(), Ref{PyPtr}()
-        # equivalent of passing C pointers &exc[1], &exc[2], &exc[3]:
-        ccall((@pysym :PyErr_Fetch), Cvoid, (Ref{PyPtr},Ref{PyPtr},Ref{PyPtr}), ptype, pvalue, ptraceback)
-        ccall((@pysym :PyErr_NormalizeException), Cvoid, (Ref{PyPtr},Ref{PyPtr},Ref{PyPtr}), ptype, pvalue, ptraceback)
-        new(msg, PyObject(ptype[]), PyObject(pvalue[]), PyObject(ptraceback[]))
-    end
-
-    PyError(msg::AbstractString, e::PyError) = new(msg, e.T, e.val, e.traceback)
```
Comment (stevengj) [inline src/exception.jl:23]: Why delete these constructors?

File: src/exception.jl [hunk 3]
```diff
@@ -44,6 +49,28 @@ function show(io::IO, e::PyError)
...
 end
 
+function pyerr_construct(msg::AbstractString)
+        ptype, pvalue, ptraceback = Ref{PyPtr}(), Ref{PyPtr}(), Ref{PyPtr}()
+        # equivalent of passing C pointers &exc[1], &exc[2], &exc[3]:
+        ccall((@pysym :PyErr_Fetch), Cvoid, (Ref{PyPtr},Ref{PyPtr},Ref{PyPtr}), ptype, pvalue, ptraceback)
+        ccall((@pysym :PyErr_NormalizeException), Cvoid, (Ref{PyPtr},Ref{PyPtr},Ref{PyPtr}), ptype, pvalue, ptraceback)
+        pyerr_construct(msg, PyObject(ptype[]), PyObject(pvalue[]), PyObject(ptraceback[]))
+end
+
```
Comment (stevengj) [inline src/exception.jl:59]: Since this mirrors the `PyError` constructor, a typical convention would be to call it `pyerror`

File: src/exception.jl [hunk 4]
```diff
@@ -44,6 +49,28 @@ function show(io::IO, e::PyError)
...
+function pyerr_construct(msg::AbstractString, e::PyError)
+    pyerr_construct(msg, e.T, e.val, e.traceback)
+end
+
+function pyerr_construct(msg::AbstractString, ptype, pvalue, ptraceback)
```
Comment (stevengj) [inline src/exception.jl:64]: Probably we should declare `ptype`, `pvalue`, and `ptraceback` as `::PyObject` since those are the only correct types to pass here?

File: src/exception.jl (hunk 2 above)
Comment (PhilipVinc) [reply src/exception.jl:23]: I check the value returned by `PyErr_Fetch` and depending on the output I build either a `PyError` or a `PyJLError`. Because of this, I figured that moving those calls outside of the constructor would be a better idea.

File: src/exception.jl (hunk 3 above)
Comment (PhilipVinc) [reply src/exception.jl:59]: `pyerr_construct` can return either a `PyError` or a `PyJlError`. So I thought that being more explicit that this might return different types was a good thing. I'll change it to pyerror if you think that's better.

File: src/exception.jl [hunk 5]
```diff
@@ -44,6 +49,28 @@ function show(io::IO, e::PyError)
...
+    args = pvalue.args
```
Comment (stevengj) [inline src/exception.jl:65]: Probably we can make this a bit more robust, and avoid unnecessary conversions.  (Rebase to get 926b931690fcf311df5729fc021430fbd1da12b8 for `_getproperty`)  Something like:
```jl
pargs = _getproperty(pvalue, "args")
if pargs != C_NULL
    args = PyObject(pargs)
    if length(args) > 0
        arg = PyObject(ccall((@pysym :PySequence_GetItem), PyPtr, (PyPtr,Int), args, 0))
        if is_pyjlwrap(arg)
            jarg = unsafe_pyjlwrap_to_objref(arg)
            jarg isa PyJlError && return jarg
        end
    end
end
return PyError(msg, ptype, pvalue, ptraceback)

File: src/exception.jl [hunk 6]
```diff
@@ -178,8 +205,10 @@ end
 function pyraise(e, bt = nothing)
     eT = typeof(e)
     pyeT = haskey(pyexc::Dict, eT) ? pyexc[eT] : pyexc[Exception]
-    ccall((@pysym :PyErr_SetString), Cvoid, (PyPtr, Cstring),
-          pyeT, string("Julia exception: ", showerror_string(e, bt)))
+
```
Comment (stevengj) [inline src/exception.jl:208]: no blank line

File: src/exception.jl (hunk 3 above)
Comment (stevengj) [reply src/exception.jl:59]: That's why it's a lower-case constructor.

You see this a lot in `Base`.  e.g. `Base.Iterators.reverse` returns either a reversed object or an `Iterators.Reverse` object.

File: src/exception.jl [hunk 7]
```diff
@@ -44,6 +49,37 @@ function show(io::IO, e::PyError)
...
+function pyerror(msg::AbstractString, ptype::PyObject, pvalue::PyObject, ptraceback::PyObject)
+    pargs = _getproperty(pvalue, "args")
+
+    # If the value of the error is a PyJlError, it was generated in a pyjlwrap callback, and
+    # we forward it.
+    if pargs != C_NULL
+        args = PyObject(pargs)
+        if length(args) > 0
+            arg = PyObject(@pycheckn ccall((@pysym :PySequence_GetItem), PyPtr, (PyPtr,Int), args, 0))
```
Comment (stevengj) [inline src/exception.jl:72]: You'll need to move up the definition of the `@pycheck*` macros in this file.

Comment (PhilipVinc) [reply src/exception.jl]: I missed your comment!.
I just moved down pyerror() but I can swap them if you prefer.

**Comment by PhilipVinc** [comment]
So... 
one error is because in [this line](https://github.com/JuliaPy/PyCall.jl/blob/a80e2fdc482e9f5b1749e99f4efbe0746b0a1f1a/src/PyCall.jl#L865)
```
        if p != NULL # for dict, set, etc.
```
NULL is not defined.

The other one is the one with Unprintable and I'm on it...

**Comment by PhilipVinc** [comment]
Ok, the second error is... very weird.

In short, the solution is removing the parametric type from `PyJlError`, which is not really needed anyway.

However, I don't understand why that is the case. So below is a small investigation on the cause. Maybe it's an underlying issue in Julia, or maybe in my implementation?

I tracked it down to exactly [this line](https://github.com/PhilipVinc/PyCall.jl/blob/0a66c738455e8a9d71e93af3f2e588ec1b6c6441/src/exception.jl#L217)
```julia
    err = PyJlError(e, bt)
```

The error also persists if I try to do
```julia
t=typeof(e) #executes ok
err = PyJlError{e}(e, bt)
```

In case it might help, this error still happens if you make Unprintable's type printable but not the value.

**Comment by stevengj** [comment]
I think if you wanted to keep the parametric type you would need an outer constructor `PyJlError(err::E, trace) where {E} = PyJlError{E}(err, trace)`?  

But I agree that a parameterized type is not needed here.

**Comment by stevengj** [comment]
> The error also persists if I try to do `t=typeof(e); err = PyJlError{e}(e, bt)`

I think you mean `err = PyJlError{t}(e, bt)`?

**Comment by stevengj** [comment]
But let's leave the type as non-parametric.

**Comment by PhilipVinc** [comment]
(Now tests are passing, except for an unrelated error which I'm not sure why shows up half the time).

> I think you mean err = PyJlError{t}(e, bt)?

Yes, indeed.
I think I understood what the problem is: I just found out that in Julia you can throw any object as an error. 

On of the tests tries throwing an Unprintable object (which is not `<:Exception`) and so it could not build a PyJlerror which was throwing again.. and so on.

**Comment by stevengj** [comment]
@tkf, hopefully this doesn't cause any problems for pyjulia?

**Comment by tkf** [comment]
Thanks for the ping. I ran PyJulia test suite with PyCall `master` and there was no problem. I looked at the patch and played with it a bit. So far it works nicely.
