### PR TITLE
fix getproperty exceptions

### LINKED ISSUE #696: Wrong error reported when accessing an attribute
Hi! I have a class that does some checking before setting an attribute value, like this (pure Python):
```python
class A:
    def __setattr__(self, name, value):
        if value == 0:
            raise ValueError(value)
        # set value...

a = A()
a.a = 5  # OK
a.a = 0  # correct error message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-7600552ca637> in <module>()
----> 1 a.a = 0

<ipython-input-6-585623315894> in __setattr__(self, name, value)
      2     def __setattr__(self, name, value):
      3         if value == 0:
----> 4             raise ValueError(value)
      5         # set value...
      6

ValueError: 0
```

However, running the same code with PyCall.jl gives a very confusing error message:
```julia
py"""
class A:
    def __setattr__(self, name, value):
        if value == 0:
            raise ValueError(value)
        # set value...
"""
a = py"A"()
a.a = 5  # OK
a.a = 0  # completely wrong exception:
ERROR: KeyError: key :a not found
Stacktrace:
 [1] setproperty!(::PyObject, ::Symbol, ::Int64) at /users/aplavin/.julia/packages/PyCall/ttONZ/src/PyCall.jl:329
 [2] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by aplavin**
this throws KeyError as before when the attribute isn't there (AttributeError in python)
when the attribute is present, but its computation throws a python exception, this PR rethrows it in julia

fixes https://github.com/JuliaPy/PyCall.jl/issues/696

### CODE REVIEW

File: src/PyCall.jl [hunk 1]
```diff
@@ -298,7 +298,13 @@ end
 function _getproperty(o::PyObject, s::Union{AbstractString,Symbol})
     ispynull(o) && throw(ArgumentError("ref of NULL PyObject"))
     p = ccall((@pysym :PyObject_GetAttrString), PyPtr, (PyPtr, Cstring), o, s)
-    p == C_NULL && pyerr_clear()
+    if p == C_NULL && pyerr_occurred()
+        e = pyerror("")
```
Comment (stevengj) [inline src/PyCall.jl:302]:
```suggestion
        e = pyerror("PyObject_GetAttrString")
```

File: src/PyCall.jl [hunk 2]
```diff
@@ -298,7 +298,13 @@ end
...
+        if e.T.__name__ != "AttributeError"
```
Comment (stevengj) [inline src/PyCall.jl:303]:
```suggestion
        if pyisinstance(e.T, @pyglobalobjptr(:PyExc_AttributeError))
```

**Comment by stevengj** [comment]
Looks good, modulo a couple of minor tweaks noted above.

**Comment by stevengj** [comment]
What is `e.T` that `pyisinstance(e.T, @pyglobalobjptr(:PyExc_AttributeError)` fails to give the expected result?

**Comment by stevengj** [comment]
What does `pyisinstance(e.T, @pyglobalobjptr(:PyExc_AttributeError))` return in those cases?

**Comment by stevengj** [comment]
Oh, I see the problem.  `e.T` is not an *instance* of `AttributeError`, it is the type itself.  So the correct check is
```jl
if PyPtr(e.T) != @pyglobalobjptr(:PyExc_AttributeError)
```
(The goal here is to avoid the string conversion.)

File: src/PyCall.jl [hunk 3]
```diff
@@ -298,7 +298,13 @@ end
 function _getproperty(o::PyObject, s::Union{AbstractString,Symbol})
     ispynull(o) && throw(ArgumentError("ref of NULL PyObject"))
     p = ccall((@pysym :PyObject_GetAttrString), PyPtr, (PyPtr, Cstring), o, s)
-    p == C_NULL && pyerr_clear()
+    if p == C_NULL && pyerr_occurred()
+        e = pyerror("PyObject_GetAttrString")
+        if !pyisinstance(e.T, @pyglobalobjptr(:PyExc_AttributeError))
```
Comment (stevengj) [inline src/PyCall.jl:303]:
```suggestion
        if e.T != @pyglobalobjptr(:PyExc_AttributeError)
```

File: src/PyCall.jl [hunk 4]
```diff
@@ -327,15 +333,17 @@ setproperty!(o::PyObject, s::Symbol, v) = _setproperty!(o,s,v)
...
-    if ispynull(o)
-        throw(ArgumentError("assign of NULL PyObject"))
-    end
-    if -1 == ccall((@pysym :PyObject_SetAttrString), Cint,
-                   (PyPtr, Cstring, PyPtr), o, s, PyObject(v))
+    ispynull(o) && throw(ArgumentError("assign of NULL PyObject"))
+    p = ccall((@pysym :PyObject_SetAttrString), Cint, (PyPtr, Cstring, PyPtr), o, s, PyObject(v))
+    if p == -1 && pyerr_occurred()
+        e = pyerror("PyObject_SetAttrString")
+        if e.T.__name__ != "AttributeError"
```
Comment (stevengj) [inline src/PyCall.jl:340]:
```suggestion
        if e.T != @pyglobalobjptr(:PyExc_AttributeError)
```

File: src/PyCall.jl [hunk 5]
```diff
@@ -298,7 +298,13 @@ end
 function _getproperty(o::PyObject, s::Union{AbstractString,Symbol})
     ispynull(o) && throw(ArgumentError("ref of NULL PyObject"))
     p = ccall((@pysym :PyObject_GetAttrString), PyPtr, (PyPtr, Cstring), o, s)
-    p == C_NULL && pyerr_clear()
+    if p == C_NULL && pyerr_occurred()
+        e = pyerror("PyObject_GetAttrString")
+        if e.T != @pyglobalobjptr(:PyExc_AttributeError)
```
Comment (stevengj) [inline src/PyCall.jl:303]:
```suggestion
        if PyPtr(e.T) != @pyglobalobjptr(:PyExc_AttributeError)
```

File: src/PyCall.jl [hunk 6]
```diff
@@ -327,15 +333,17 @@ setproperty!(o::PyObject, s::Symbol, v) = _setproperty!(o,s,v)
...
-    if ispynull(o)
-        throw(ArgumentError("assign of NULL PyObject"))
-    end
-    if -1 == ccall((@pysym :PyObject_SetAttrString), Cint,
-                   (PyPtr, Cstring, PyPtr), o, s, PyObject(v))
+    ispynull(o) && throw(ArgumentError("assign of NULL PyObject"))
+    p = ccall((@pysym :PyObject_SetAttrString), Cint, (PyPtr, Cstring, PyPtr), o, s, PyObject(v))
+    if p == -1 && pyerr_occurred()
+        e = pyerror("PyObject_SetAttrString")
+        if e.T != @pyglobalobjptr(:PyExc_AttributeError)
```
Comment (stevengj) [inline src/PyCall.jl:340]:
```suggestion
        if PyPtr(e.T) != @pyglobalobjptr(:PyExc_AttributeError)
```
